version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
    volumes:
      - ./data:/var/lib/mysql
