// <auto-generated />
using System;
using HotChocolate.Checker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotChocolate.Checker.Migrations
{
    [DbContext(typeof(CheckerDbContext))]
    [Migration("20230711163102_AddGenreEntity")]
    partial class AddGenreEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "3508472828551",
                            Language = "ADP",
                            PageCount = 6472,
                            PublicationDate = new DateTime(2023, 5, 20, 15, 29, 37, 889, DateTimeKind.Local).AddTicks(6018),
                            Title = "Kreiger - Abernathy"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            ISBN = "6509583864169",
                            Language = "Incredible",
                            PageCount = 8780,
                            PublicationDate = new DateTime(2023, 3, 5, 22, 8, 30, 245, DateTimeKind.Local).AddTicks(3607),
                            Title = "Wintheiser - Miller"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            ISBN = "4970010577914",
                            Language = "invoice",
                            PageCount = 1638,
                            PublicationDate = new DateTime(2023, 5, 2, 12, 4, 36, 848, DateTimeKind.Local).AddTicks(9679),
                            Title = "Johnson LLC"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            ISBN = "9336162113625",
                            Language = "Avon",
                            PageCount = 5925,
                            PublicationDate = new DateTime(2022, 12, 18, 2, 9, 17, 386, DateTimeKind.Local).AddTicks(9940),
                            Title = "Pacocha Inc"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            ISBN = "5736686165249",
                            Language = "Senior",
                            PageCount = 7389,
                            PublicationDate = new DateTime(2023, 6, 29, 11, 33, 7, 932, DateTimeKind.Local).AddTicks(2970),
                            Title = "Weimann, Langosh and McCullough"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            ISBN = "7522709389123",
                            Language = "logistical",
                            PageCount = 5452,
                            PublicationDate = new DateTime(2023, 1, 19, 3, 3, 45, 967, DateTimeKind.Local).AddTicks(7733),
                            Title = "Renner Group"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            ISBN = "4989958874337",
                            Language = "Bedfordshire",
                            PageCount = 7714,
                            PublicationDate = new DateTime(2023, 2, 25, 4, 23, 28, 628, DateTimeKind.Local).AddTicks(7433),
                            Title = "Hodkiewicz - Volkman"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            ISBN = "6063823056498",
                            Language = "web-readiness",
                            PageCount = 5268,
                            PublicationDate = new DateTime(2023, 3, 25, 22, 4, 29, 779, DateTimeKind.Local).AddTicks(8897),
                            Title = "Collier - MacGyver"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            ISBN = "8444163248480",
                            Language = "generating",
                            PageCount = 9066,
                            PublicationDate = new DateTime(2023, 3, 1, 8, 38, 28, 850, DateTimeKind.Local).AddTicks(6496),
                            Title = "Bode, Morar and McLaughlin"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            ISBN = "2275043239283",
                            Language = "Louisiana",
                            PageCount = 8039,
                            PublicationDate = new DateTime(2023, 3, 3, 6, 4, 52, 834, DateTimeKind.Local).AddTicks(9006),
                            Title = "Krajcik LLC"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            ISBN = "1920042043706",
                            Language = "Soft",
                            PageCount = 4626,
                            PublicationDate = new DateTime(2023, 4, 9, 3, 9, 8, 400, DateTimeKind.Local).AddTicks(3273),
                            Title = "Osinski and Sons"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 12,
                            ISBN = "7019732649947",
                            Language = "Movies, Beauty & Shoes",
                            PageCount = 9574,
                            PublicationDate = new DateTime(2022, 7, 16, 2, 5, 23, 240, DateTimeKind.Local).AddTicks(2630),
                            Title = "Predovic - Barton"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 13,
                            ISBN = "9123201510244",
                            Language = "Games & Computers",
                            PageCount = 9922,
                            PublicationDate = new DateTime(2022, 10, 23, 8, 54, 52, 519, DateTimeKind.Local).AddTicks(663),
                            Title = "Johns Inc"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 14,
                            ISBN = "5537508118517",
                            Language = "engage",
                            PageCount = 2841,
                            PublicationDate = new DateTime(2022, 7, 22, 16, 42, 26, 240, DateTimeKind.Local).AddTicks(4434),
                            Title = "Torp - Schaefer"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            ISBN = "7652383596880",
                            Language = "protocol",
                            PageCount = 5400,
                            PublicationDate = new DateTime(2023, 2, 5, 18, 50, 19, 655, DateTimeKind.Local).AddTicks(7618),
                            Title = "Mayer, Simonis and DuBuque"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            ISBN = "1913220210250",
                            Language = "firmware",
                            PageCount = 7250,
                            PublicationDate = new DateTime(2023, 6, 29, 21, 12, 33, 470, DateTimeKind.Local).AddTicks(3181),
                            Title = "Grimes, Kilback and Koss"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 17,
                            ISBN = "1875574921421",
                            Language = "reciprocal",
                            PageCount = 3296,
                            PublicationDate = new DateTime(2023, 3, 5, 4, 18, 24, 577, DateTimeKind.Local).AddTicks(8595),
                            Title = "Krajcik LLC"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 18,
                            ISBN = "8697958197108",
                            Language = "implementation",
                            PageCount = 264,
                            PublicationDate = new DateTime(2023, 6, 16, 7, 13, 27, 999, DateTimeKind.Local).AddTicks(7489),
                            Title = "Spencer and Sons"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 19,
                            ISBN = "7229529914978",
                            Language = "Practical Wooden Fish",
                            PageCount = 6001,
                            PublicationDate = new DateTime(2023, 6, 23, 20, 6, 15, 709, DateTimeKind.Local).AddTicks(1746),
                            Title = "Armstrong, Franecki and Collier"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 20,
                            ISBN = "1627078464535",
                            Language = "fresh-thinking",
                            PageCount = 4147,
                            PublicationDate = new DateTime(2023, 6, 25, 13, 27, 50, 213, DateTimeKind.Local).AddTicks(2141),
                            Title = "Grady, Torphy and Dach"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 21,
                            ISBN = "4961375238268",
                            Language = "hack",
                            PageCount = 7102,
                            PublicationDate = new DateTime(2023, 2, 24, 21, 23, 35, 692, DateTimeKind.Local).AddTicks(7219),
                            Title = "Wiegand, Cormier and Conn"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 22,
                            ISBN = "0448718451200",
                            Language = "cultivate",
                            PageCount = 8405,
                            PublicationDate = new DateTime(2023, 2, 1, 4, 9, 13, 81, DateTimeKind.Local).AddTicks(3081),
                            Title = "Schinner - Ferry"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 23,
                            ISBN = "6561754059941",
                            Language = "deposit",
                            PageCount = 1857,
                            PublicationDate = new DateTime(2022, 7, 19, 0, 10, 21, 990, DateTimeKind.Local).AddTicks(9019),
                            Title = "Lowe, Botsford and Brakus"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 24,
                            ISBN = "6402399660140",
                            Language = "Delaware",
                            PageCount = 360,
                            PublicationDate = new DateTime(2023, 2, 15, 21, 51, 11, 679, DateTimeKind.Local).AddTicks(2756),
                            Title = "Dooley and Sons"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 25,
                            ISBN = "1081432318290",
                            Language = "Ferry",
                            PageCount = 1869,
                            PublicationDate = new DateTime(2022, 12, 8, 8, 59, 51, 497, DateTimeKind.Local).AddTicks(8024),
                            Title = "Moen - Hauck"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 26,
                            ISBN = "5242848340015",
                            Language = "TCP",
                            PageCount = 7480,
                            PublicationDate = new DateTime(2022, 9, 11, 13, 1, 0, 761, DateTimeKind.Local).AddTicks(6213),
                            Title = "Cummerata Group"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 27,
                            ISBN = "0655725658663",
                            Language = "Practical Fresh Car",
                            PageCount = 3609,
                            PublicationDate = new DateTime(2022, 11, 30, 21, 27, 32, 774, DateTimeKind.Local).AddTicks(3148),
                            Title = "Powlowski - Emard"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 28,
                            ISBN = "5813154829817",
                            Language = "national",
                            PageCount = 746,
                            PublicationDate = new DateTime(2022, 7, 20, 5, 38, 37, 119, DateTimeKind.Local).AddTicks(6268),
                            Title = "Rau and Sons"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 29,
                            ISBN = "4979132417818",
                            Language = "Spring",
                            PageCount = 2431,
                            PublicationDate = new DateTime(2023, 1, 13, 2, 40, 55, 279, DateTimeKind.Local).AddTicks(2687),
                            Title = "Veum, Willms and McLaughlin"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 30,
                            ISBN = "8231461100943",
                            Language = "program",
                            PageCount = 687,
                            PublicationDate = new DateTime(2022, 11, 21, 5, 45, 16, 106, DateTimeKind.Local).AddTicks(6998),
                            Title = "Hagenes - Robel"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 31,
                            ISBN = "7161790853597",
                            Language = "silver",
                            PageCount = 6472,
                            PublicationDate = new DateTime(2023, 4, 12, 14, 56, 19, 148, DateTimeKind.Local).AddTicks(9501),
                            Title = "Wyman and Sons"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 32,
                            ISBN = "1766118042033",
                            Language = "connecting",
                            PageCount = 4798,
                            PublicationDate = new DateTime(2022, 9, 27, 0, 46, 39, 331, DateTimeKind.Local).AddTicks(8039),
                            Title = "Kautzer - Kuvalis"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 33,
                            ISBN = "3421696888012",
                            Language = "Producer",
                            PageCount = 3294,
                            PublicationDate = new DateTime(2022, 9, 10, 22, 10, 45, 411, DateTimeKind.Local).AddTicks(5540),
                            Title = "Haley and Sons"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 34,
                            ISBN = "5814936253806",
                            Language = "Cotton",
                            PageCount = 6103,
                            PublicationDate = new DateTime(2023, 6, 7, 6, 33, 49, 287, DateTimeKind.Local).AddTicks(7413),
                            Title = "Williamson, Wolff and Labadie"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 35,
                            ISBN = "2957643792503",
                            Language = "Union",
                            PageCount = 5913,
                            PublicationDate = new DateTime(2023, 6, 13, 2, 15, 44, 497, DateTimeKind.Local).AddTicks(5687),
                            Title = "Schmeler - Bogisich"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 36,
                            ISBN = "1133790419796",
                            Language = "forecast",
                            PageCount = 8013,
                            PublicationDate = new DateTime(2022, 11, 2, 0, 2, 22, 945, DateTimeKind.Local).AddTicks(2755),
                            Title = "Fahey, Weissnat and Wolff"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 37,
                            ISBN = "2756126043725",
                            Language = "tan",
                            PageCount = 2919,
                            PublicationDate = new DateTime(2022, 11, 21, 15, 16, 13, 957, DateTimeKind.Local).AddTicks(3057),
                            Title = "Parker - Hackett"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 38,
                            ISBN = "0550609819140",
                            Language = "Roads",
                            PageCount = 6512,
                            PublicationDate = new DateTime(2023, 4, 19, 18, 13, 52, 662, DateTimeKind.Local).AddTicks(9684),
                            Title = "Howell Inc"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 39,
                            ISBN = "1697566548443",
                            Language = "24/365",
                            PageCount = 6521,
                            PublicationDate = new DateTime(2022, 10, 25, 3, 59, 9, 187, DateTimeKind.Local).AddTicks(8954),
                            Title = "Kuvalis and Sons"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 40,
                            ISBN = "7886570529102",
                            Language = "Representative",
                            PageCount = 3849,
                            PublicationDate = new DateTime(2022, 12, 14, 18, 6, 7, 430, DateTimeKind.Local).AddTicks(7914),
                            Title = "Jacobson and Sons"
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 41,
                            ISBN = "8206249232307",
                            Language = "concept",
                            PageCount = 5162,
                            PublicationDate = new DateTime(2023, 5, 8, 15, 41, 38, 27, DateTimeKind.Local).AddTicks(5645),
                            Title = "Nicolas - Langworth"
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 42,
                            ISBN = "5048968995797",
                            Language = "Unbranded",
                            PageCount = 9029,
                            PublicationDate = new DateTime(2022, 8, 29, 12, 25, 56, 248, DateTimeKind.Local).AddTicks(5047),
                            Title = "McLaughlin Group"
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 43,
                            ISBN = "2907240358695",
                            Language = "generating",
                            PageCount = 5020,
                            PublicationDate = new DateTime(2023, 2, 13, 15, 30, 42, 660, DateTimeKind.Local).AddTicks(8134),
                            Title = "Keeling - O'Conner"
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 44,
                            ISBN = "9794369142709",
                            Language = "Public-key",
                            PageCount = 6645,
                            PublicationDate = new DateTime(2022, 10, 11, 17, 28, 16, 293, DateTimeKind.Local).AddTicks(8717),
                            Title = "McDermott - Schmitt"
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 45,
                            ISBN = "9911074894383",
                            Language = "Colorado",
                            PageCount = 266,
                            PublicationDate = new DateTime(2022, 12, 21, 7, 17, 52, 732, DateTimeKind.Local).AddTicks(5061),
                            Title = "Abernathy - Blick"
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 46,
                            ISBN = "2396784117026",
                            Language = "mindshare",
                            PageCount = 2977,
                            PublicationDate = new DateTime(2023, 6, 9, 8, 46, 9, 521, DateTimeKind.Local).AddTicks(4532),
                            Title = "Reichert - Koepp"
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 47,
                            ISBN = "2619064213639",
                            Language = "Mall",
                            PageCount = 6673,
                            PublicationDate = new DateTime(2022, 12, 28, 3, 0, 29, 906, DateTimeKind.Local).AddTicks(7776),
                            Title = "Rau, Berge and Zemlak"
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 48,
                            ISBN = "1778130445525",
                            Language = "Ergonomic Granite Computer",
                            PageCount = 7545,
                            PublicationDate = new DateTime(2022, 11, 3, 16, 28, 6, 803, DateTimeKind.Local).AddTicks(1514),
                            Title = "Schiller, Fisher and Hauck"
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 49,
                            ISBN = "5654469990003",
                            Language = "Practical",
                            PageCount = 5167,
                            PublicationDate = new DateTime(2022, 11, 28, 22, 22, 41, 783, DateTimeKind.Local).AddTicks(9673),
                            Title = "Quigley and Sons"
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 50,
                            ISBN = "2223104075509",
                            Language = "Clothing",
                            PageCount = 7795,
                            PublicationDate = new DateTime(2022, 9, 14, 16, 48, 17, 701, DateTimeKind.Local).AddTicks(4126),
                            Title = "Lubowitz - Littel"
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 51,
                            ISBN = "1499444416192",
                            Language = "Personal Loan Account",
                            PageCount = 2007,
                            PublicationDate = new DateTime(2023, 3, 21, 14, 25, 33, 99, DateTimeKind.Local).AddTicks(9802),
                            Title = "Shields Group"
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 52,
                            ISBN = "7227181650739",
                            Language = "Corners",
                            PageCount = 8294,
                            PublicationDate = new DateTime(2022, 9, 16, 1, 16, 25, 473, DateTimeKind.Local).AddTicks(499),
                            Title = "Moore - Emard"
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 53,
                            ISBN = "4315879141409",
                            Language = "bypassing",
                            PageCount = 169,
                            PublicationDate = new DateTime(2023, 5, 9, 6, 53, 14, 711, DateTimeKind.Local).AddTicks(5453),
                            Title = "Kuvalis, Swift and Marquardt"
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 54,
                            ISBN = "1276265140884",
                            Language = "Rue",
                            PageCount = 3965,
                            PublicationDate = new DateTime(2022, 12, 19, 10, 37, 10, 220, DateTimeKind.Local).AddTicks(620),
                            Title = "Hackett, Reynolds and White"
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 55,
                            ISBN = "8344715759221",
                            Language = "engage",
                            PageCount = 2909,
                            PublicationDate = new DateTime(2023, 3, 17, 6, 52, 4, 44, DateTimeKind.Local).AddTicks(7715),
                            Title = "Gislason - Halvorson"
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 56,
                            ISBN = "7465570660956",
                            Language = "synthesizing",
                            PageCount = 9678,
                            PublicationDate = new DateTime(2022, 11, 19, 13, 28, 55, 661, DateTimeKind.Local).AddTicks(9204),
                            Title = "Weissnat, Baumbach and Ernser"
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 57,
                            ISBN = "7869769515759",
                            Language = "approach",
                            PageCount = 4536,
                            PublicationDate = new DateTime(2022, 11, 25, 13, 33, 2, 231, DateTimeKind.Local).AddTicks(1375),
                            Title = "Bahringer, Murazik and Tillman"
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 58,
                            ISBN = "0779185351008",
                            Language = "alliance",
                            PageCount = 3584,
                            PublicationDate = new DateTime(2023, 4, 28, 19, 11, 59, 250, DateTimeKind.Local).AddTicks(3945),
                            Title = "Schiller - Towne"
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 59,
                            ISBN = "4615459590499",
                            Language = "core",
                            PageCount = 6680,
                            PublicationDate = new DateTime(2023, 4, 27, 23, 44, 31, 761, DateTimeKind.Local).AddTicks(6513),
                            Title = "Farrell Inc"
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 60,
                            ISBN = "8614811437355",
                            Language = "Web",
                            PageCount = 1292,
                            PublicationDate = new DateTime(2023, 1, 22, 23, 48, 40, 357, DateTimeKind.Local).AddTicks(1567),
                            Title = "Rolfson - Little"
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 61,
                            ISBN = "4355973624132",
                            Language = "District",
                            PageCount = 8017,
                            PublicationDate = new DateTime(2022, 11, 24, 16, 56, 43, 134, DateTimeKind.Local).AddTicks(7917),
                            Title = "Pacocha LLC"
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 62,
                            ISBN = "9528415549255",
                            Language = "Lead",
                            PageCount = 7568,
                            PublicationDate = new DateTime(2023, 5, 22, 18, 16, 4, 271, DateTimeKind.Local).AddTicks(3497),
                            Title = "Rutherford - Wintheiser"
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 63,
                            ISBN = "3718217653618",
                            Language = "Intelligent Granite Chips",
                            PageCount = 5914,
                            PublicationDate = new DateTime(2023, 4, 5, 9, 8, 43, 810, DateTimeKind.Local).AddTicks(3555),
                            Title = "Funk, Rempel and Koch"
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 64,
                            ISBN = "4402318396312",
                            Language = "payment",
                            PageCount = 9892,
                            PublicationDate = new DateTime(2022, 11, 8, 19, 59, 25, 844, DateTimeKind.Local).AddTicks(8197),
                            Title = "Ward - Deckow"
                        },
                        new
                        {
                            Id = 65,
                            AuthorId = 65,
                            ISBN = "8966000262553",
                            Language = "Cambridgeshire",
                            PageCount = 8104,
                            PublicationDate = new DateTime(2022, 7, 27, 14, 15, 8, 747, DateTimeKind.Local).AddTicks(1320),
                            Title = "Kertzmann Inc"
                        },
                        new
                        {
                            Id = 66,
                            AuthorId = 66,
                            ISBN = "0032571553401",
                            Language = "deposit",
                            PageCount = 2842,
                            PublicationDate = new DateTime(2023, 6, 18, 3, 19, 49, 904, DateTimeKind.Local).AddTicks(1845),
                            Title = "Pacocha Inc"
                        },
                        new
                        {
                            Id = 67,
                            AuthorId = 67,
                            ISBN = "9877083532909",
                            Language = "calculate",
                            PageCount = 9057,
                            PublicationDate = new DateTime(2022, 10, 17, 2, 46, 53, 134, DateTimeKind.Local).AddTicks(1296),
                            Title = "Stoltenberg Inc"
                        },
                        new
                        {
                            Id = 68,
                            AuthorId = 68,
                            ISBN = "6799939312196",
                            Language = "Belize Dollar",
                            PageCount = 9463,
                            PublicationDate = new DateTime(2022, 8, 23, 22, 53, 27, 242, DateTimeKind.Local).AddTicks(9310),
                            Title = "Toy, Torp and Bednar"
                        },
                        new
                        {
                            Id = 69,
                            AuthorId = 69,
                            ISBN = "1867513513347",
                            Language = "invoice",
                            PageCount = 7747,
                            PublicationDate = new DateTime(2022, 10, 10, 8, 48, 17, 363, DateTimeKind.Local).AddTicks(5931),
                            Title = "Reilly - Jacobs"
                        },
                        new
                        {
                            Id = 70,
                            AuthorId = 70,
                            ISBN = "5713091109013",
                            Language = "directional",
                            PageCount = 2692,
                            PublicationDate = new DateTime(2022, 11, 28, 0, 10, 49, 540, DateTimeKind.Local).AddTicks(3594),
                            Title = "Armstrong - Kemmer"
                        },
                        new
                        {
                            Id = 71,
                            AuthorId = 71,
                            ISBN = "9497940038070",
                            Language = "Forks",
                            PageCount = 9609,
                            PublicationDate = new DateTime(2023, 1, 7, 11, 57, 43, 935, DateTimeKind.Local).AddTicks(673),
                            Title = "Runte - Moen"
                        },
                        new
                        {
                            Id = 72,
                            AuthorId = 72,
                            ISBN = "3514667028156",
                            Language = "Assurance",
                            PageCount = 833,
                            PublicationDate = new DateTime(2023, 3, 24, 5, 19, 7, 756, DateTimeKind.Local).AddTicks(1186),
                            Title = "Bradtke Group"
                        },
                        new
                        {
                            Id = 73,
                            AuthorId = 73,
                            ISBN = "6094997352086",
                            Language = "indigo",
                            PageCount = 5755,
                            PublicationDate = new DateTime(2022, 9, 4, 22, 21, 34, 696, DateTimeKind.Local).AddTicks(9111),
                            Title = "Braun - Morissette"
                        },
                        new
                        {
                            Id = 74,
                            AuthorId = 74,
                            ISBN = "4007586454339",
                            Language = "South Africa",
                            PageCount = 1062,
                            PublicationDate = new DateTime(2023, 5, 16, 21, 31, 18, 404, DateTimeKind.Local).AddTicks(70),
                            Title = "Tillman - Ryan"
                        },
                        new
                        {
                            Id = 75,
                            AuthorId = 75,
                            ISBN = "2296247731007",
                            Language = "withdrawal",
                            PageCount = 9665,
                            PublicationDate = new DateTime(2023, 3, 31, 15, 26, 59, 53, DateTimeKind.Local).AddTicks(9484),
                            Title = "Rempel - McDermott"
                        },
                        new
                        {
                            Id = 76,
                            AuthorId = 76,
                            ISBN = "5057869658687",
                            Language = "Unbranded",
                            PageCount = 5357,
                            PublicationDate = new DateTime(2023, 3, 31, 15, 39, 8, 606, DateTimeKind.Local).AddTicks(6941),
                            Title = "Hoppe, Lindgren and Koss"
                        },
                        new
                        {
                            Id = 77,
                            AuthorId = 77,
                            ISBN = "3506321494735",
                            Language = "monitor",
                            PageCount = 9871,
                            PublicationDate = new DateTime(2023, 5, 10, 16, 13, 54, 87, DateTimeKind.Local).AddTicks(1237),
                            Title = "Franecki Group"
                        },
                        new
                        {
                            Id = 78,
                            AuthorId = 78,
                            ISBN = "9270337192490",
                            Language = "incentivize",
                            PageCount = 3703,
                            PublicationDate = new DateTime(2022, 8, 20, 17, 55, 48, 558, DateTimeKind.Local).AddTicks(6919),
                            Title = "Reilly - Wiza"
                        },
                        new
                        {
                            Id = 79,
                            AuthorId = 79,
                            ISBN = "1273502431804",
                            Language = "ability",
                            PageCount = 7262,
                            PublicationDate = new DateTime(2023, 4, 2, 13, 18, 16, 772, DateTimeKind.Local).AddTicks(5456),
                            Title = "Kilback LLC"
                        },
                        new
                        {
                            Id = 80,
                            AuthorId = 80,
                            ISBN = "4600440706300",
                            Language = "THX",
                            PageCount = 5272,
                            PublicationDate = new DateTime(2023, 1, 31, 11, 16, 4, 317, DateTimeKind.Local).AddTicks(6212),
                            Title = "Bradtke, Kertzmann and Walsh"
                        },
                        new
                        {
                            Id = 81,
                            AuthorId = 81,
                            ISBN = "7244173613299",
                            Language = "Representative",
                            PageCount = 3583,
                            PublicationDate = new DateTime(2023, 6, 21, 4, 54, 26, 477, DateTimeKind.Local).AddTicks(7270),
                            Title = "Satterfield - Huel"
                        },
                        new
                        {
                            Id = 82,
                            AuthorId = 82,
                            ISBN = "4763682163604",
                            Language = "Grocery & Electronics",
                            PageCount = 2989,
                            PublicationDate = new DateTime(2022, 10, 30, 23, 16, 32, 555, DateTimeKind.Local).AddTicks(840),
                            Title = "VonRueden - Hilll"
                        },
                        new
                        {
                            Id = 83,
                            AuthorId = 83,
                            ISBN = "2744508188454",
                            Language = "Credit Card Account",
                            PageCount = 857,
                            PublicationDate = new DateTime(2022, 10, 5, 16, 26, 24, 78, DateTimeKind.Local).AddTicks(3433),
                            Title = "Bode Group"
                        },
                        new
                        {
                            Id = 84,
                            AuthorId = 84,
                            ISBN = "9635436531708",
                            Language = "New Caledonia",
                            PageCount = 5637,
                            PublicationDate = new DateTime(2022, 8, 20, 0, 43, 46, 273, DateTimeKind.Local).AddTicks(9994),
                            Title = "Williamson LLC"
                        },
                        new
                        {
                            Id = 85,
                            AuthorId = 85,
                            ISBN = "9479313412014",
                            Language = "Balboa",
                            PageCount = 4904,
                            PublicationDate = new DateTime(2022, 10, 29, 3, 14, 37, 584, DateTimeKind.Local).AddTicks(1675),
                            Title = "Lindgren, Howell and Walter"
                        },
                        new
                        {
                            Id = 86,
                            AuthorId = 86,
                            ISBN = "5676958236911",
                            Language = "deposit",
                            PageCount = 4566,
                            PublicationDate = new DateTime(2023, 1, 20, 8, 36, 32, 837, DateTimeKind.Local).AddTicks(3176),
                            Title = "Klein Group"
                        },
                        new
                        {
                            Id = 87,
                            AuthorId = 87,
                            ISBN = "0463738753707",
                            Language = "Central African Republic",
                            PageCount = 6474,
                            PublicationDate = new DateTime(2023, 2, 26, 13, 38, 58, 584, DateTimeKind.Local).AddTicks(6438),
                            Title = "Bechtelar Inc"
                        },
                        new
                        {
                            Id = 88,
                            AuthorId = 88,
                            ISBN = "9899889236461",
                            Language = "capacitor",
                            PageCount = 9735,
                            PublicationDate = new DateTime(2022, 12, 25, 19, 30, 33, 767, DateTimeKind.Local).AddTicks(1801),
                            Title = "Schuster, Schimmel and Gleichner"
                        },
                        new
                        {
                            Id = 89,
                            AuthorId = 89,
                            ISBN = "2651095991575",
                            Language = "Rupiah",
                            PageCount = 183,
                            PublicationDate = new DateTime(2022, 11, 18, 5, 58, 31, 684, DateTimeKind.Local).AddTicks(746),
                            Title = "Oberbrunner - Feeney"
                        },
                        new
                        {
                            Id = 90,
                            AuthorId = 90,
                            ISBN = "6870957025166",
                            Language = "actuating",
                            PageCount = 6881,
                            PublicationDate = new DateTime(2023, 1, 31, 23, 55, 17, 252, DateTimeKind.Local).AddTicks(2229),
                            Title = "Feest, Hoeger and Hickle"
                        },
                        new
                        {
                            Id = 91,
                            AuthorId = 91,
                            ISBN = "9568747895040",
                            Language = "teal",
                            PageCount = 2003,
                            PublicationDate = new DateTime(2022, 9, 17, 3, 57, 7, 165, DateTimeKind.Local).AddTicks(5199),
                            Title = "Beer - Metz"
                        },
                        new
                        {
                            Id = 92,
                            AuthorId = 92,
                            ISBN = "7376023793285",
                            Language = "Coordinator",
                            PageCount = 9312,
                            PublicationDate = new DateTime(2023, 5, 19, 23, 4, 46, 593, DateTimeKind.Local).AddTicks(9514),
                            Title = "Little, Zemlak and Beier"
                        },
                        new
                        {
                            Id = 93,
                            AuthorId = 93,
                            ISBN = "4427667211505",
                            Language = "Awesome Steel Pants",
                            PageCount = 4773,
                            PublicationDate = new DateTime(2022, 11, 21, 3, 36, 55, 221, DateTimeKind.Local).AddTicks(9580),
                            Title = "Bernhard - Bechtelar"
                        },
                        new
                        {
                            Id = 94,
                            AuthorId = 94,
                            ISBN = "9741525331767",
                            Language = "Mountain",
                            PageCount = 1440,
                            PublicationDate = new DateTime(2023, 5, 15, 13, 3, 35, 682, DateTimeKind.Local).AddTicks(7453),
                            Title = "Schmitt - O'Connell"
                        },
                        new
                        {
                            Id = 95,
                            AuthorId = 95,
                            ISBN = "3733841680359",
                            Language = "auxiliary",
                            PageCount = 5109,
                            PublicationDate = new DateTime(2023, 6, 9, 6, 32, 47, 914, DateTimeKind.Local).AddTicks(9004),
                            Title = "Ferry Group"
                        },
                        new
                        {
                            Id = 96,
                            AuthorId = 96,
                            ISBN = "2503474453016",
                            Language = "enterprise",
                            PageCount = 5023,
                            PublicationDate = new DateTime(2022, 12, 24, 2, 32, 40, 135, DateTimeKind.Local).AddTicks(9830),
                            Title = "Welch, Roob and Wisoky"
                        },
                        new
                        {
                            Id = 97,
                            AuthorId = 97,
                            ISBN = "9148689884618",
                            Language = "copying",
                            PageCount = 5319,
                            PublicationDate = new DateTime(2022, 8, 26, 23, 51, 9, 447, DateTimeKind.Local).AddTicks(9300),
                            Title = "Reichel, D'Amore and Beatty"
                        },
                        new
                        {
                            Id = 98,
                            AuthorId = 98,
                            ISBN = "8724639906725",
                            Language = "Marketing",
                            PageCount = 8532,
                            PublicationDate = new DateTime(2023, 5, 22, 11, 47, 0, 916, DateTimeKind.Local).AddTicks(6150),
                            Title = "Keebler, Bashirian and Yundt"
                        },
                        new
                        {
                            Id = 99,
                            AuthorId = 99,
                            ISBN = "8145918364379",
                            Language = "teal",
                            PageCount = 1585,
                            PublicationDate = new DateTime(2023, 5, 25, 15, 12, 36, 116, DateTimeKind.Local).AddTicks(1895),
                            Title = "Schulist and Sons"
                        });
                });

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.GenreBooksConnectionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("GenreId");

                    b.ToTable("GenreBooksConnectionEntity");
                });

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GenreEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Stage And Screen"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Latin"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Funk"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = 16,
                            Name = "World"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Non Music"
                        },
                        new
                        {
                            Id = 21,
                            Name = "World"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Funk"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Jazz"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Stage And Screen"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 35,
                            Name = "World"
                        },
                        new
                        {
                            Id = 36,
                            Name = "World"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Latin"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Electronic"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 53,
                            Name = "World"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Funk"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Latin"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Hip Hop"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Country"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Non Music"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Stage And Screen"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Non Music"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Non Music"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Pop"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Stage And Screen"
                        },
                        new
                        {
                            Id = 82,
                            Name = "World"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Classical"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Folk"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 90,
                            Name = "World"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Soul"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Rap"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Blues"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Stage And Screen"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Reggae"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Blues"
                        });
                });

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Marjorie",
                            SurName = "Reynolds"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bryant",
                            SurName = "Kunde"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Damon",
                            SurName = "Collins"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jerald",
                            SurName = "Denesik"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Brett",
                            SurName = "Kohler"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jill",
                            SurName = "Nitzsche"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Douglas",
                            SurName = "Schowalter"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Randall",
                            SurName = "Hilpert"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pete",
                            SurName = "Windler"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Elena",
                            SurName = "Wolf"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jean",
                            SurName = "Sipes"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sophia",
                            SurName = "Carter"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Lana",
                            SurName = "Hilll"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Vicky",
                            SurName = "Balistreri"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Andrew",
                            SurName = "Kemmer"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Hope",
                            SurName = "Krajcik"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ervin",
                            SurName = "Hyatt"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Christopher",
                            SurName = "Kuvalis"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Carroll",
                            SurName = "Hane"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Philip",
                            SurName = "Stark"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Frederick",
                            SurName = "Raynor"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Blanche",
                            SurName = "Zboncak"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ramon",
                            SurName = "Schiller"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Max",
                            SurName = "Pagac"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Vincent",
                            SurName = "Jacobs"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Lorraine",
                            SurName = "Waelchi"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Jasmine",
                            SurName = "Abbott"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Jacqueline",
                            SurName = "Dach"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Clifton",
                            SurName = "Powlowski"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Darrel",
                            SurName = "Rutherford"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Wendell",
                            SurName = "Fay"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Charlene",
                            SurName = "Williamson"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ruth",
                            SurName = "Shields"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Heather",
                            SurName = "Hauck"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Minnie",
                            SurName = "Torphy"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Donna",
                            SurName = "Nicolas"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Roberta",
                            SurName = "Muller"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Daryl",
                            SurName = "Zulauf"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Ernesto",
                            SurName = "Mayert"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Spencer",
                            SurName = "Hagenes"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Nelson",
                            SurName = "Hahn"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Rickey",
                            SurName = "Waters"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Penny",
                            SurName = "Kemmer"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Marlene",
                            SurName = "Runolfsson"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Herman",
                            SurName = "Satterfield"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Austin",
                            SurName = "Kling"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Michele",
                            SurName = "Dooley"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Harry",
                            SurName = "Robel"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Angie",
                            SurName = "Russel"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Brittany",
                            SurName = "Bogisich"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Margarita",
                            SurName = "Reichel"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Roy",
                            SurName = "King"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Christy",
                            SurName = "Schneider"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Mack",
                            SurName = "Simonis"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Alton",
                            SurName = "Bartoletti"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Bradley",
                            SurName = "Schowalter"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Curtis",
                            SurName = "Cole"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Everett",
                            SurName = "Reichel"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Jonathon",
                            SurName = "MacGyver"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Angelina",
                            SurName = "Auer"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Yvette",
                            SurName = "Walter"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Vernon",
                            SurName = "Flatley"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Shane",
                            SurName = "Keebler"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Noah",
                            SurName = "Hahn"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Claude",
                            SurName = "Gibson"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Wilbert",
                            SurName = "Hilll"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Amanda",
                            SurName = "Zboncak"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Edwin",
                            SurName = "Pacocha"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Tim",
                            SurName = "Hintz"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Hilda",
                            SurName = "Daniel"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Rickey",
                            SurName = "Purdy"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Maxine",
                            SurName = "Nienow"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Reginald",
                            SurName = "Schumm"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Kathy",
                            SurName = "Kuhlman"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Pam",
                            SurName = "Kunze"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Rolando",
                            SurName = "Watsica"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Jessie",
                            SurName = "Goyette"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Tasha",
                            SurName = "Olson"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Michelle",
                            SurName = "Marquardt"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Carrie",
                            SurName = "Buckridge"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Ramiro",
                            SurName = "Dietrich"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Dora",
                            SurName = "Wiza"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Jack",
                            SurName = "Deckow"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Wilson",
                            SurName = "Schaden"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Alonzo",
                            SurName = "Watsica"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Bob",
                            SurName = "Wiza"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Miguel",
                            SurName = "Hudson"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Mitchell",
                            SurName = "Hegmann"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Judy",
                            SurName = "Wilderman"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Dan",
                            SurName = "Abernathy"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Lamar",
                            SurName = "Monahan"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Dennis",
                            SurName = "O'Connell"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Alice",
                            SurName = "Heller"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Renee",
                            SurName = "Bogisich"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Rhonda",
                            SurName = "Skiles"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Renee",
                            SurName = "Bernhard"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Kurt",
                            SurName = "Wyman"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Rick",
                            SurName = "Goodwin"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Jackie",
                            SurName = "Harvey"
                        });
                });

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.BookEntity", b =>
                {
                    b.HasOne("HotChocolate.Checker.Persistence.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.GenreBooksConnectionEntity", b =>
                {
                    b.HasOne("HotChocolate.Checker.Persistence.Entities.BookEntity", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotChocolate.Checker.Persistence.Entities.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
